### ISSUE TITLE
Process pooling not battery friendly

### ISSUE THREAD

**Issue by u1735067** [YJesus/AntiRansom#2]
Process pooling doesn't seems to be battery friendly, consuming a lot of CPU.

![image](https://cloud.githubusercontent.com/assets/1735067/16770032/570525e4-484b-11e6-9b82-28278a29a9ba.png)

Could something else be used ?
Like : 
http://www.online-tech-tips.com/windows-xp/how-to-track-and-monitor-who-and-when-someone-accesses-a-folder-on-your-computer/
https://stackoverflow.com/questions/3517460/is-there-anything-like-inotify-on-windows
?

Also, but not sure bout this, SumatraPDF could open one of those PDF file without being detected (between 2 pooling I guess).

**Comment by YJesus** [comment]
Hi,

Probably the problem is the sleep() part. If I increase the time, AR uses less resources but you lose reliability

The techniques explained in this URLs aren't useful due the lack of capability of identify process that touch files

I think NtQuerySystemInformation is -for now- the best option

As regards of SumatraPDF, It's not detected because I suppose SumatraPDF open the PDF then read the file and then close the file, so the handle of the PDF file is short lived and not maintained opened.. 

You can do the test, open a file with SumatraPDF and after that, try to delete the file. If you can do it, the handle was closed.

Ransomware needs to open many files of the Honey Folder, so is always detected because when AntiRansom searches for open files, there are always any file opened by Ransomware
